name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 3.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  nb_utils:
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  tap_to_expand:
  flutter_rating_bar:
  ionicons:
  dropdown_search:
  
  # Media
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  photo_view: ^0.14.0
  appinio_video_player: ^1.2.1
  video_player: ^2.6.1
  visibility_detector: ^0.4.0+2
  camera:
  extended_image: ^8.1.1
  
  #Date CountDown
  date_count_down:
  flutter_timer_countdown:
  flutter_staggered_grid_view: 

  # APIs
  http:
  intl: ^0.18.0
  html: ^0.15.3

  flutter_html:
  # google_mobile_ads: ^3.0.0

  # State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  get:

  # Share
  flutter_custom_tabs: ^1.0.4
  flutter_secure_storage:

  # Firebase
  google_mlkit_face_detection:
  google_mlkit_text_recognition:

  # AUTHENTICATION
  the_apple_sign_in: ^1.1.1 
  jwt_decoder:

  signalr_netcore:
  webview_flutter:

  #SlideShow
  flutter_image_slideshow: any
  carousel_slider: ^4.2.1
  
  # Story
  numberpicker: 
  input_quantity:

  path_provider: ^2.0.15
  connectivity_plus:
  lottie: ^2.3.2

  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  mobx_codegen: ^2.3.0
  flutter_launcher_icons:

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/
    - banks.json

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  # image_path_android: "assets/app_icon.png"
  # image_path_ios: "assets/app_icon.png"
  android: "ic_launcher"
  ios: true
  adaptive_icon_background: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true
